name: manual

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Set up Java SDK
        uses: actions/setup-java@3.13.0
        with:
              java-version: "17"
              distribution: "adopt"

      - name: Run with Gradle
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: DroneApp
          path: app/build/outputs/apk/app-debug.apk
