name: manual

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Set up Java SDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "adopt"
      
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          build-tools: 30.0.3

      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > ./local.properties

      - name: Run with Gradle
        env:
          ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
        run: ./gradlew build -PmapsApiKey=${{ secrets.MAPS_API_KEY }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: DroneApp
          path: app/build/outputs/apk/app-debug.apk
